[phases.setup]
nixPkgs = ["python310", "gcc", "libpq", "pkg-config"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt --only-binary=:all: --prefer-binary"
]

[start]
cmd = "python bot.py"
